config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  # User routes
  namespace :admin do
    resources :users, only: :index
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  resources :program_types, only:[:new, :create] do
    resources :organization_program_types, only: [:create, :destroy]
  end
  # get '/program_types/new', to: 'program_types#new', as: ''

  get '/', to: 'home#index', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  get '/programs/0_5', to: 'programs#index0_5'
  get '/programs/0_5/:type', to: 'programs#index0_5'
  # get '/programs/0_5/sports', to: 'programs#index0_5'
  # get '/programs/0_5/education', to: 'programs#index0_5'
  # get '/programs/0_5/parent_child', to: 'programs#index0_5'
  # get '/programs/0_5/childcare', to: 'programs#index0_5'

  get '/programs/6_12', to: 'programs#index6_12'
  get '/programs/6_12/:type', to: 'programs#index6_12'
  # get '/programs/6_12/sports', to: 'programs#index6_12'
  # get '/programs/6_12/education', to: 'programs#index6_12'
  # get '/programs/6_12/community', to: 'programs#index6_12'
  # get '/programs/6_12/childcare', to: 'programs#index6_12'

  get '/services/pregnancy_babies/:type', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/help_crisis', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/health', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/support', to: 'services#pregnancy_babies'

  get '/services/families/:type', to: 'services#families'
  # get '/services/families/help_crisis', to: 'services#families'
  # get '/services/families/childcare', to: 'services#families'
  # get '/services/families/assistance', to: 'services#families'
  # get '/services/families/support', to: 'services#families'

  get '/services/children/:type', to: 'services#children'
  # get '/services/children/help_crisis', to: 'services#children'
  # get '/services/children/child_advocacy', to: 'services#children'
  # get '/services/children/health', to: 'services#children'
  # get '/services/children/support', to: 'services#children'

  get '/programs/learn_more/:id', to: 'programs#learn_more', as: 'program_learn_more'
  get '/services/learn_more/:id', to: 'services#learn_more', as: 'service_learn_more'
  get '/events/learn_more/:id', to: 'events#learn_more', as: 'event_learn_more'
  get '/whats_new_items/learn_more/:id', to: 'whats_new_items#learn_more', as: 'whats_new_item_learn_more'

  get '/services/pregnancy_babies', to: 'services#pregnancy_babies'

  get '/services/families', to: 'services#families'

  get '/services/children', to: 'services#children'

  get '/live', to: 'home#live', as: 'live5210'

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard/pending_and_approved_events', to: 'events#pending_and_approved_events'
  get '/dashboard/pending_and_approved_resources', to: 'resources#pending_and_approved_resources'
  get '/dashboard/manage_programs', to: 'programs#index'
  get '/dashboard/manage_services', to: 'services#index'
  get '/dashboard/manage_tags', to: 'tags#index'
  get '/dashboard/manage_organizations', to: 'organizations#index'
  get '/dashboard/manage_events', to: 'events#index2'
  get '/dashboard/manage_whats_new_items', to: 'whats_new_items#index'
  get '/dashboard/manage_resources', to: 'resources#index2'

  get '/map', to: 'home#map', as: 'map'

  # get '/search', to: 'home#search', as: 'search'
  # post '/search', to: 'home#search'

  get '/surveys', to: 'home#surveys', as: 'surveys'

  get '/contact_submit', to: 'home#submit', as: 'contact_submit'
  match '/contact_mail', to: 'home#contact_mail', via: 'post'

  get 'dashboard/pending_and_approved_events/decline/:id', to: 'events#decline', as: 'decline_event'
  match '/decline_event_mail', to: 'events#decline_mail', via: 'post'

  get 'dashboard/pending_and_approved_resources/decline/:id', to: 'resources#decline', as: 'decline_resource'
  match '/decline_resource_mail', to: 'resources#decline_mail', via: 'post'

  match '/events/:id/admin_approve_resource', to: 'resources#admin_approve_resource', as: 'admin_resource_approve', via: 'post'

  match '/events/:id/admin_approve_event', to: 'events#admin_approve_event', as: 'admin_event_approve', via: 'post'




  resources :tags
  resources :resources
  resources :whats_new_items
  resources :services
  resources :events
  resources :organizations
  resources :programs
  resources :password_resets

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  has_scope :by_start_date
  has_scope :by_end_date
  has_scope :search
  has_scope :approved
  has_scope :event_location, type: :array
  has_scope :registration, type: :array
  has_scope :cost, type: :array
  has_scope :age_group, type: :array
  has_scope :program_type, type: :array
  has_scope :event_type, type: :array
  has_scope :category, type: :array
  has_scope :service_type, type: :array

  def index
    @whats_new_items_random = WhatsNewItem.all.limit(3).order("RANDOM()")
  end

  def about
  end

  def contact_mail
    if verify_recaptcha
      name = params[:name]
      email = params[:email]
      message = params[:message]
      ContactUsMailer.contact_email(name, email, message).deliver
      redirect_to contact_submit_path, notice: 'Message sent'
    else
      flash.now[:alert] = "Please complete the Captacha to send a message."
      render :contact
    end
  end

  def live

  end

  def submit

  end

  def dashboard
    @pending_and_approved_events = Event.where(:approved => false || nil)
    @pending_and_approved_resources = Resource.where(:approved => false || nil)
  end

  def surveys

  end

  def map
    @events = apply_scopes(Event.approved, event_params).all
    @programs = apply_scopes(Program, program_params).all
    @services = apply_scopes(Service, service_params).all

    @all_results =
      @events.order(title: :asc) +
        @programs.includes(:organization).order("organizations.name asc") +
        @services.includes(:organization).order("organizations.name asc")

    @map_search_results = Kaminari.paginate_array(@all_results).page(params[:page]).per(5)


    @hash1 = Gmaps4rails.build_markers(@all_results) do |event, marker|
      if event.has_attribute?(:event_type_id)
        concat_event_info = "
      <p class='bree-font26'>#{event.title}</p>
      <br>
      <img src='#{event.image_url.to_s}' class='img-responsive' style='width:100%;height:250px;object-fit: cover'></img>
      <br>
      <p class='font-16'>#{event.description}</p>
      <p class='font-16'>#{event.address}</p>
      <a class='event-info-bold2 font-16' href='events/learn_more/#{event.id}'>Learn More</a>"
        marker.lat event.latitude
        marker.lng event.longitude
        marker.infowindow concat_event_info

      elsif event.has_attribute?(:program_type_id)
        concat_program_info = "
      <p class='bree-font26'>#{event.organization.name}</p>
      <br>
      <img src='#{event.image_url.to_s}' class='img-responsive' style='width:100%;height:250px;object-fit: cover'></img>
      <br>
      <p class='font-16'>#{event.program_description}</p>
      <p class='font-16'>#{event.organization.address}</p>
      <a class='event-info-bold2 font-16' href='programs/learn_more/#{event.id}'>Learn More</a>"

        marker.lat event.organization.latitude
        marker.lng event.organization.longitude
        marker.infowindow concat_program_info
      elsif event.has_attribute?(:service_type_id)
        concat_service_info = "
      <p class='bree-font26'>#{event.organization.name}</p>
      <br>
      <img src='#{event.image_url.to_s}' class='img-responsive' style='width:100%;height:250px;object-fit: cover'></img>
      <br>
      <p class='font-16'>#{event.service_description}</p>
      <p class='font-16'>#{event.organization.address}</p>
      <a class='event-info-bold2 font-16' href='services/learn_more/#{event.id}'>Learn More</a>"
        marker.lat event.organization.latitude
        marker.lng event.organization.longitude
        marker.infowindow concat_service_info
      end
    end

  end

  def search

  end

  def whatsnew

  end

  private

  def event_params
    params.slice(:search, :by_start_date, :by_end_date, :approved, :event_location, :registration, :cost, :age_group, :event_type)
  end

  def program_params
    params.slice(:search, :age_group, :program_type, :cost, :registration)
  end

  def service_params
    params.slice(:search, :category, :service_type)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div class="wholePage">
  <div class="container-fluid contact-us-body">
    <div class="container" id="boyrunning-container">
      <img src="https://delta-kids-bucket.s3.us-west-2.amazonaws.com/static_assets/BoyRunning.jpeg" id='boyrunning'/>      
      <h1 class="mobile-font-24" id="contact-us-text">CONTACT US</h1>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">

        <div class="col-xs-12 col-sm-8 col-md-8">
          <div class="container-fluid" id="contact-box">
            <p class="font-16">Do you have any questions or want to learn more about a specific subject? Drop us a
              line.</p>
            <br>

            <%= form_tag(contact_mail_path) do %>

              <div class="flex form-group">
                <%= text_field_tag :name, nil, { placeholder: "Name", class: "form-control contact-form" } %>
                &nbsp;&nbsp;&nbsp;
                <%= text_field_tag :email, nil, { placeholder: "Email", class: "form-control contact-form" } %>
              </div>
              <div class="contact-form">
                <%= text_area_tag :message, nil, { placeholder: "Message", class: "form-control contact-form", rows: 10 } %>
              </div>
              <%= submit_tag 'Send Message', class: "btn-primary pull-right btn-lg", id: "btn-padding" %>
              <br>
              <%= recaptcha_tags %>
            <% end %>


          </div>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4">
          <div class="container-fluid" id="about-us-box">
            <p class="bree-font" style="font-size:26px;">About us</p>            
            <img src="https://delta-kids-bucket.s3.us-west-2.amazonaws.com/static_assets/jumbotron-about-us.svg", id="jumbo-about-us"/>
            <p class="font-16">DeltaKids is a coalition of community partners. We work together to build Delta's
              capacity as a child-friendly community where all children thrive.</p>
            <a href="<%= about_path %>" class="pull-right">Learn More<span class="caret caret-right"></span></a>
          </div>
        </div>

      </div>
    </div>

  </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/home/index.html.erb
<!-- Home Page -->
<!-- First section div -->
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="section1 section1-container clouds-background" style="background-size: contain;
        background-position: center; background-repeat:no-repeat">
      <div class="row section1-text">
        <div class="col-xs-12 col-sm-12 col-md-12">

          <div class="hidden-xs col-sm-1 col-md-1"></div>
          <div class="col-xs-12 col-sm-5 col-md-5">
            <p id='welcome-line1'>Welcome to
            <p>
            <p id='welcome-line2'>Delta Kids
            <p>
          </div>
          <div class="col-xs-12 col-sm-5 col-md-5 subsection">
            <p id='welcome-line3'>We are your One-Stop-Info-Shop</p>
            <p id='welcome-line4'> for children 0-12 years in Delta, BC.
            <p>
              <%= button_to "LEARN MORE", about_path, :method => "get", id: 'button-learnmore' %>
          </div>
          <div class="hidden-xs col-sm-1 col-md-1"></div>
        </div>
      </div>
    </div>


    <!-- Second section div -->
    <div class="section2" id="pad-200">
      <div class="container-fluid section2-container">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <%= image_tag "kids.png", class: "kids-image" %>
        </div>
      </div>
    </div>


    <!-- Third section div -->
    <div class="section3 section1-container" id="link-to-cal">
      <div class="container-fluid section3-background">
        <div class="section1-text">
          <div class="hidden-xs col-sm-1 col-md-1"></div>
          <div class="col-xs-12 col-sm-5 col-md-5">
            <%= image_tag "calendar.svg", class: "calendar-image" %>
          </div>
          <div class="col-xs-12 col-sm-5 col-md-5 subsection">
            <p id='section3-line1'>Be "in the know" </p>
            <p id='section3-line2'> for events and activities
            <p>
            <p id='section3-line3'> in your community.
            <p>
              <%= button_to "GO TO ACTIVITIES CALENDAR", events_path, :method => "get", id: 'button-activities-cal' %>
              <!-- <div id='button-activities-cal'><a href="<%= events_path %>" class="about-us" style="color: white;">GO TO ACTIVITIES CALENDAR</a></div> -->
          </div>
          <div class="hidden-xs col-sm-1 col-md-1"></div>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="background-color" style="text-align: center; padding-top:0px">
      <p class="bree-font" style="background-color:white;color:#004b80;margin:0;z-index:2;position:relative">To take part in our survey, please click
        <a href="https://forms.gle/9GJFfzLEoa2kkqdK8" target="_blank" style="color:#00A3DA">here</a></p>
      <%= image_tag("cloud1.png", style: "width:100%;height:150px; position:relative; bottom:60px;") %>
    </div>

    <!-- Fourth section div -->
    <%= render 'partials/whatsnew' %>

    <!-- Fifth section div -->

    <div class="col-xs-12 col-sm-12 col-md-12 background-color center-flex-content">
      <br>
      <a href="<%= map_path %>"><%= image_tag('bus.png', style: "width:100%; padding-left:10%; padding-right:10%") %></a>
    </div>
  </div>
</div>

app/views/home/map.html.erb
<script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
<script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHDSOM8UnLFbt2SQYhPg2ZY7GQ601JS5Y"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>


<!-- First section div -->
<div class="wholePage">
  <div class="calendar-section1 calendar-section1-container" id="calendar-section1">
    <div class="row">
      <div class="col-xs-12 col-sm-12 hidden-md hidden-lg" style="padding-left:5%;padding-right:5%">

        <button type="button" class="btn btn-primary" id="map_filter-btn" data-toggle="modal" data-target="#mapFilterModal" style="width:100%; margin-top:20px;">
          Filter
        </button>

        <!-- Modal -->
        <div class="modal fade" id="mapFilterModal" tabindex="-1" role="dialog" aria-labelledby="mapFilterModalTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header" style="background-color:#144c81">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:white">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body background-color" >
                <%= render "partials/mobile_map_filter" %>
              </div>
              <div class="modal-footer" style="background-color:#144c81">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row calendar-row">
      <div class="hidden-xs hidden-sm col-md-3" id="calendar-subsection1">
        <%= render 'partials/map_filter' %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-9 calendar-subsection2" style='padding-top:40px'>

        <div class="calendar-subsection2-card">
          <div id="map">
            <div id="multi_markers" style="width:100%; height:100%"></div>
          </div>

          <script type="text/javascript">
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'multi_markers'}}, function(){
            markers = handler.addMarkers(<%=raw @hash1.to_json %>);
            handler.bounds.extendWith(markers);
            handler.map.centerOn ({lat:49.0952,lng:-123.0265});
            handler.getMap().setZoom(11);
          });</script>


          <div class="calendar-subsection2-text">
            <p class="calendar-subsection2-header bree-font">Map of Delta</p>
            <div class="calendar-subsection2-text" style="background-color: #fff">
              <div class="calendar-subsection2-details">
                <p class="font-20">This is Delta. It includes the communities of Tsawwassen, Ladner, and North Delta.
                  On the north side it is bordered by the Fraser River and 96th Avenue.
                  On the east side, it is bordered by Scott Road (or 120th Street).</p>
                </div>
              </div>
            </div>
          </div>

          <div class="container-fluid">
            <a id="results"></a>
            <p class="bree-font">Additional Resources</p>
            <div class="calendar-subsection2-details">
              <p class="calendar-subsection2-header2 bree-font26">Deltaassist Family & Community Services</p>
              <p class="font-16">Online directory of community services.</p>
              <div class="event-info">
                <p class="font-16">604-594-3455</p>
                <p class="font-16">9097 120 Street, Delta B.C. V4C 6R7</p>
              </div>
              <a class="font-16" href="http://www.deltaassist.com/about-deltassist/find-a-service">http://www.deltaassist.com/about-deltassist/find-a-service</a>
            </div>
            <br>
            <div class="calendar-subsection2-details">
              <p class="calendar-subsection2-header2 bree-font26">BC211</p>
              <p class="font-16">Referalls and online directory of community services.</p>
              <div class="event-info">
                <p class="font-16">Call 211</p>
                <p class="font-16">Delta, BC</p>
              </div>
              <a class="font-16" href="http://redbookonline.bc211.ca/">http://redbookonline.bc211.ca/</a>
            </div>
          </div>


          <div class="container-fluid">
            <br>
            <p class="bree-font">Results (<%= @map_search_results.total_count %>)</p>
            <% for event in @map_search_results %>
            <% if event.has_attribute?(:event_type_id) %>
            <div class="calendar-subsection2-card light-blue-bg-color" style="margin-top:30px">
              <div class="calendar-subsection2-text" style="background-color: #fff">
                <div class="calendar-subsection2-details">
                  <p class="calendar-subsection2-header2 bree-font26"><%= event.title %></p>
                  <div class="event-info">
                    <div class="">
                      <%= image_tag "icon-calendar.svg", class: "event-info-icon" %>
                      <p class="event-info-txt-bold">Date:</p>
                      <p class="event-info-txt"><%= event.start_time.strftime("%m/%d/%Y") %></p>
                      <p class="event-info-txt"> - <%= event.end_time.strftime("%m/%d/%Y") %></p>
                    </div>
                    <div class="">
                      <%= image_tag "icon-clock.svg", class: "event-info-icon" %>
                      <% if event.start_time %>
                      <p class="event-info-txt"><%= event.start_time.strftime("%I:%M %p") %></p>
                      <% end %>
                      <% if event.end_time %>
                      <p class="event-info-txt"> - <%= event.end_time.strftime("%I:%M %p") %></p>
                      <% end %>
                    </div>
                    <div class="">
                      <%= image_tag "icon-baby.svg", class: "event-info-icon" %>
                      <% event.age_groups.each do |age| %>
                      <p class="event-info-txt"><%= age.age %></p>
                      <% end %>
                    </div>
                    <div class="">
                      <%= image_tag "icon-tag.svg", class: "event-info-icon" %>
                      <p class="event-info-txt"><%= event.cost %></p>
                    </div>
                    <div class="">
                      <%= image_tag "icon-location-pin.svg", class: "event-info-icon" %>
                      <p class="event-info-txt"><%= event.location_names %></p>
                    </div>
                  </div>
                  <p class="ellipsis-3 font-16"><%= event.description %></p>
                  <p class="font-16"><%= event.address %></p>
                  <div class="event-info2">
                    <p><%= link_to 'Learn More', event_learn_more_path(event), class: "event-info-bold2 font-16" %></p>
                    <%= image_tag "cursor.svg", class: "event-info-icon2" %>
                  </div>
                </div>
              </div>
            </div>
            <% elsif event.has_attribute?(:program_type_id) %>
            <div class="calendar-subsection2-card light-blue-bg-color" style="margin-top:30px">
              <div class="calendar-subsection2-text" style="background-color: #fff">
                <div class="calendar-subsection2-details">
                  <p class="calendar-subsection2-header2 bree-font26"><%= event.organization.name %></p>
                  <div class="flex" style="">
                    <div class="" style="">
                      <i class="fa fa-info-circle event-info-icon" style="color:#00A3DE; font-size:1.3em"></i>
                      <p class="event-info-txt"><%= event.program_type.name %></p>
                    </div>
                    &nbsp&nbsp
                    <div class="">
                      <%= image_tag "icon-baby.svg", class: "event-info-icon" %>
                      <% event.age_groups.each do |age| %>
                      <p class="event-info-txt"><%= age.age %></p>
                      <% end %>
                    </div>
                  </div>
                  <div class="">
                    <p class="ellipsis-3 font-16"><%= event.program_description %></p>
                  </div>
                  <div class="">
                    <p class="font-16">
                      <%= event.organization.address %>
                    </p>
                  </div>
                  <div class="event-info2">
                    <p><%= link_to 'Learn More', program_learn_more_path(event), class: "event-info-bold2 font-16" %></p>
                    <%= image_tag "cursor.svg", class: "event-info-icon2" %>
                  </div>
                </div>
              </div>
            </div>
            <% elsif event.has_attribute?(:service_type_id) %>
            <div class="calendar-subsection2-card light-blue-bg-color" style="margin-top:30px">
              <div class="calendar-subsection2-text" style="background-color: #fff">
                <div class="calendar-subsection2-details">
                  <p class="calendar-subsection2-header2 bree-font26"><%= event.organization.name %></p>
                  <div class="flex" style="">
                    <div class="">
                      <i class="fa fa-info-circle event-info-icon" style="color:#00A3DE;font-size:1.3em"></i>
                      <p class="event-info-txt"><%= event.service_type.name %></p>
                    </div>
                  </div>
                  <p class="ellipsis-3 font-16"><%= event.service_description %></p>
                  <div class="event-info">
                    <p class="font-16"><%= event.organization.address %></p>
                  </div>
                  <div class="event-info2">
                    <p><%= link_to 'Learn More', service_learn_more_path(event), class: "event-info-bold2 font-16" %></p>
                    <%= image_tag "cursor.svg", class: "event-info-icon2" %>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
          <div class="container-fluid center-flex-content bree-font" style="align-items:center;">
            <%= paginate @map_search_results, window: 2, :params => {:anchor => "results"} %>
          </div>

        </div>
      </div>
      <script>

      let checkboxValues = JSON.parse(localStorage.getItem('checkboxValues')) || {},
      $checkboxes = $(".checkbox-container :checkbox");

      $checkboxes.on("change", function(){
        $checkboxes.each(function(){
          checkboxValues[this.id] = this.checked;
        });

        localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));
      });

      // On page load
      $.each(checkboxValues, function(key, value) {
        $("#" + key).prop('checked', value);
      });
      </script>

app/views/home/pending_and_approved_events.html.erb
<div class="wholePage">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 content">

        <%= render 'partials/dash_sidebar' %>

        <div class="col-md-9 dash-main-content" style="background-color:white;">
          <% if user_signed_in? %>
          <% if is_admin? %>
          <div class="row">
            <div class="col-md-12">
              
              <h1 class="queue-header">Pending Events</h1>

              <div class="table-responsive">

                <table class="table table-bordered table-hover" style="text-align:center;">
                  <thead>
                    <tr>
                      <th>Event</th>
                      <th>Location</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Drop in Soccer</td>
                      <td>Delta</td>
                      <td><button class="btn btn-default">Approve</button>
                        <button class="btn btn-default">Decline</button></td>
                      </tr>
                      <tr>
                        <td>Drop in Soccer</td>
                        <td>Delta</td>
                        <td><button class="btn btn-default">Approve</button>
                          <button class="btn btn-default">Decline</button></td>
                        </tr>
                        <tr>
                          <td>Drop in Soccer</td>
                          <td>Delta</td>
                          <td><button class="btn btn-default">Approve</button>
                            <button class="btn btn-default">Decline</button></td>
                          </tr>
                          <tr>
                            <td>Drop in Soccer</td>
                            <td>Delta</td>
                            <td><button class="btn btn-default">Approve</button>
                              <button class="btn btn-default">Decline</button></td>
                            </tr>
                            <tr>
                              <td>Drop in Soccer</td>
                              <td>Delta</td>
                              <td><button class="btn btn-default">Approve</button>
                                <button class="btn btn-default">Decline</button></td>
                              </tr>
                            </tbody>
                          </table>

                          <h1 class="queue-header">Approved Events</h1>

                          <table class="table table-bordered table-hover" style="text-align:center;">
                            <thead>
                              <tr>
                                <th>Event</th>
                                <th>Location</th>
                                <th>Actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td>Drop in Soccer</td>
                                <td>Delta</td>
                                <td><button class="btn btn-default">Delete</button>
                                </tr>
                                <tr>
                                  <td>Drop in Soccer</td>
                                  <td>Delta</td>
                                  <td><button class="btn btn-default">Delete</button>
                                  </tr>
                                  <tr>
                                    <td>Drop in Soccer</td>
                                    <td>Delta</td>
                                    <td><button class="btn btn-default">Delete</button>
                                    </tr>
                                    <tr>
                                      <td>Drop in Soccer</td>
                                      <td>Delta</td>
                                      <td><button class="btn btn-default">Delete</button>
                                      </tr>
                                      <tr>
                                        <td>Drop in Soccer</td>
                                        <td>Delta</td>
                                        <td><button class="btn btn-default">Delete</button>
                                        </tr>
                                      </tbody>
                                    </table>

                                  </div>
                                </div>
                              </div>
                              <% end %>
                              <% else %>
                              <div>
                                <p>
                                  Dashboard section is meant to publish a Resource and/or Event. In order to proceed you must have an account with us. Please Log In or create a New User.
                                  <br>
                                  <!-- <%= link_to 'New User', signup_path, class: 'top-right-panel' %>&nbsp -->
                                  <!-- <div class="">
                                  <%= link_to 'Log In', login_path, class: 'top-right-panel' %>&nbsp
                                </div> -->
                              </p>
                              <br>
                              <p>
                                If you don't want to proceed, please feel free to go elsewhere in our site.
                              </p>
                            </div>
                          </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>

                  <!-- Rainbow Footer-->

                  <%= render 'partials/footer' %>