config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  # User routes
  namespace :admin do
    resources :users, only: :index
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  resources :program_types, only:[:new, :create] do
    resources :organization_program_types, only: [:create, :destroy]
  end
  # get '/program_types/new', to: 'program_types#new', as: ''

  get '/', to: 'home#index', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  get '/programs/0_5', to: 'programs#index0_5'
  get '/programs/0_5/:type', to: 'programs#index0_5'
  # get '/programs/0_5/sports', to: 'programs#index0_5'
  # get '/programs/0_5/education', to: 'programs#index0_5'
  # get '/programs/0_5/parent_child', to: 'programs#index0_5'
  # get '/programs/0_5/childcare', to: 'programs#index0_5'

  get '/programs/6_12', to: 'programs#index6_12'
  get '/programs/6_12/:type', to: 'programs#index6_12'
  # get '/programs/6_12/sports', to: 'programs#index6_12'
  # get '/programs/6_12/education', to: 'programs#index6_12'
  # get '/programs/6_12/community', to: 'programs#index6_12'
  # get '/programs/6_12/childcare', to: 'programs#index6_12'

  get '/services/pregnancy_babies/:type', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/help_crisis', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/health', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/support', to: 'services#pregnancy_babies'

  get '/services/families/:type', to: 'services#families'
  # get '/services/families/help_crisis', to: 'services#families'
  # get '/services/families/childcare', to: 'services#families'
  # get '/services/families/assistance', to: 'services#families'
  # get '/services/families/support', to: 'services#families'

  get '/services/children/:type', to: 'services#children'
  # get '/services/children/help_crisis', to: 'services#children'
  # get '/services/children/child_advocacy', to: 'services#children'
  # get '/services/children/health', to: 'services#children'
  # get '/services/children/support', to: 'services#children'

  get '/programs/learn_more/:id', to: 'programs#learn_more', as: 'program_learn_more'
  get '/services/learn_more/:id', to: 'services#learn_more', as: 'service_learn_more'
  get '/events/learn_more/:id', to: 'events#learn_more', as: 'event_learn_more'
  get '/whats_new_items/learn_more/:id', to: 'whats_new_items#learn_more', as: 'whats_new_item_learn_more'

  get '/services/pregnancy_babies', to: 'services#pregnancy_babies'

  get '/services/families', to: 'services#families'

  get '/services/children', to: 'services#children'

  get '/live', to: 'home#live', as: 'live5210'

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard/pending_and_approved_events', to: 'events#pending_and_approved_events'
  get '/dashboard/pending_and_approved_resources', to: 'resources#pending_and_approved_resources'
  get '/dashboard/manage_programs', to: 'programs#index'
  get '/dashboard/manage_services', to: 'services#index'
  get '/dashboard/manage_tags', to: 'tags#index'
  get '/dashboard/manage_organizations', to: 'organizations#index'
  get '/dashboard/manage_events', to: 'events#index2'
  get '/dashboard/manage_whats_new_items', to: 'whats_new_items#index'
  get '/dashboard/manage_resources', to: 'resources#index2'

  get '/map', to: 'home#map', as: 'map'

  # get '/search', to: 'home#search', as: 'search'
  # post '/search', to: 'home#search'

  get '/surveys', to: 'home#surveys', as: 'surveys'

  get '/contact_submit', to: 'home#submit', as: 'contact_submit'
  match '/contact_mail', to: 'home#contact_mail', via: 'post'

  get 'dashboard/pending_and_approved_events/decline/:id', to: 'events#decline', as: 'decline_event'
  match '/decline_event_mail', to: 'events#decline_mail', via: 'post'

  get 'dashboard/pending_and_approved_resources/decline/:id', to: 'resources#decline', as: 'decline_resource'
  match '/decline_resource_mail', to: 'resources#decline_mail', via: 'post'

  match '/events/:id/admin_approve_resource', to: 'resources#admin_approve_resource', as: 'admin_resource_approve', via: 'post'

  match '/events/:id/admin_approve_event', to: 'events#admin_approve_event', as: 'admin_event_approve', via: 'post'




  resources :tags
  resources :resources
  resources :whats_new_items
  resources :services
  resources :events
  resources :organizations
  resources :programs
  resources :password_resets

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :OrganizationTaggings, dependent: :destroy
  has_many :organizations, through: :OrganizationTaggings

  has_many :ResourceTaggings, dependent: :destroy
  has_many :resources, through: :ResourceTaggings

  has_many :EventTaggings, dependent: :destroy
  has_many :events, through: :EventTaggings

  validates :name, uniqueness: true

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:show, :edit, :update, :destroy]

  # ONLY ADMIN
  def index
    @tags = Tag.all.order(name: :asc).page(params[:page]).per(50)
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new tag_params
    if @tag.save
      flash[:notice] = 'Tag Created'
      redirect_to tag_path(@tag)
    else
      flash.now[:alert] = @tag.pretty_errors
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag.update(tag_params)
    redirect_to @tag, notice: "Successfully Updated"
  end

  def destroy
    if is_admin?
      @tag.destroy
      redirect_to tags_path, notice: "Tag Deleted!"
    else
      flash[:alert] = "Access Denied"
      redirect_to @tag
    end
  end

  private

  def tag_params
    params.require(:tag).permit([:name])
  end

  def find_tag
    @tag = Tag.find params[:id]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<div class="wholePage">
  <!-- First section div -->
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">
      <%= render 'partials/dash_sidebar' %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white;">
        <% if user_signed_in? %>
          <% if is_admin? %>
            <div class="">
              <br>
              <p class="dashboard-headers mobile-font-24">Edit Tag</p>
              <%= form_for @tag do |f| %>
                <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
                  <%= f.text_field :name, class: 'form form-control', :required => true %>
                </div>
                <br>
                <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field" style="padding-bottom:10%;">
                  <%= f.submit class: 'btn btn-primary form-control  ' %>
                </div>
                <br>
              <% end %>
          <% else %>
            <%= render 'partials/login_msg' %>
          <% end %>
        <% else %>
          <%= render 'partials/login_msg' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/tags/index.html.erb
<div class="wholePage">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">
      <%= render 'partials/dash_sidebar' %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white;">
        <% if user_signed_in? %>
          <% if is_admin? %>
            <div class="container-fluid">
              <h1 class="bree-font">Tags</h1>
              <br>
              <% @tags.each do |tag| %>
                <%= link_to tag.name, tag_path(tag), class: "font-16" %>
                <span class="pull-right">ID: <%= tag.id %></span>
                <hr>
              <% end %>
              <div class="container-fluid center-flex-content bree-font" style="align-items:center;">
                <%= paginate @tags, window: 2 %>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= render 'partials/login_msg' %>
          </div>
        <% end %>
        </div>
  </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/tags/new.html.erb
<div class="wholePage">
  <!-- First section div -->
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">
      <%= render 'partials/dash_sidebar' %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white;">
        <% if user_signed_in? %>
          <% if is_admin? %>
            <div class="">
              <br>
              <p class="dashboard-headers mobile-font-24">Create a New Tag</p>
              <%= form_for @tag do |f| %>
                <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
                  <%= f.text_field :name, class: 'form form-control', :required => true %>
                </div>
                <br>
                <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field" style="padding-bottom:10%;">
                  <%= f.submit class: 'btn btn-primary form-control  ' %>
                </div>
                <br>
              <% end %>
          <% else %>
            <%= render 'partials/login_msg' %>
          <% end %>
        <% else %>
          <%= render 'partials/login_msg' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Rainbow Footer-->
<%= render 'partials/footer' %>

app/views/tags/show.html.erb
<div class="wholePage">
  <div class="row">
    <div class="col-xs-12 content">

      <%= render 'partials/dash_sidebar' %>

      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white;">
        <% if user_signed_in? %>
          <div class="col-xs-12">
            <div class="container-fluid">
              <br>

              <p class="bree-font">Tag</p>
              <p class='font-20'><strong>Tag ID: </strong><%= @tag.id %></p>
              <p class="font-20" style="white-space: pre-line;"><strong>Tag Name: </strong><%= @tag.name %></p>
              <br>
              <% if is_admin? %>
                <div class="center-flex-content">

                  <%= link_to 'Edit', edit_tag_path(@tag),
                              class: 'btn btn-success form-padding edit-delete-btn-width',style:"margin-right:5%;"  %>

                  <%= link_to 'Delete', tag_path(@tag),
                              method: :delete,
                              data: {confirm: 'Are you sure?'},
                              class: 'btn btn-danger edit-delete-btn-width', style:'color:white !important;' %>
                </div>
                <br>
              <% end %>
            </div>
          </div>
        <% else %>
          <div>
            <p>
              Dashboard section is meant to publish a Resource and/or Event. In order to proceed you must have an account with us. Please Log In or create a New User.
              <br>
              <!-- <%= link_to 'New User', signup_path, class: 'top-right-panel' %>&nbsp -->
              <!-- <div class="">
            <%= link_to 'Log In', login_path, class: 'top-right-panel' %>&nbsp
          </div> -->
            </p>
            <br>
            <p>
              If you don't want to proceed, please feel free to go elsewhere in our site.
            </p>
          </div>
          </div>
        <% end %>
        </div>
  </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>