config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'password_resets/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  # User routes
  namespace :admin do
    resources :users, only: :index
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  resources :program_types, only:[:new, :create] do
    resources :organization_program_types, only: [:create, :destroy]
  end
  # get '/program_types/new', to: 'program_types#new', as: ''

  get '/', to: 'home#index', as: 'home'
  get '/about', to: 'home#about', as: 'about'
  get '/contact', to: 'home#contact', as: 'contact'

  get '/programs/0_5', to: 'programs#index0_5'
  get '/programs/0_5/:type', to: 'programs#index0_5'
  # get '/programs/0_5/sports', to: 'programs#index0_5'
  # get '/programs/0_5/education', to: 'programs#index0_5'
  # get '/programs/0_5/parent_child', to: 'programs#index0_5'
  # get '/programs/0_5/childcare', to: 'programs#index0_5'

  get '/programs/6_12', to: 'programs#index6_12'
  get '/programs/6_12/:type', to: 'programs#index6_12'
  # get '/programs/6_12/sports', to: 'programs#index6_12'
  # get '/programs/6_12/education', to: 'programs#index6_12'
  # get '/programs/6_12/community', to: 'programs#index6_12'
  # get '/programs/6_12/childcare', to: 'programs#index6_12'

  get '/services/pregnancy_babies/:type', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/help_crisis', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/health', to: 'services#pregnancy_babies'
  # get '/services/pregnancy_babies/support', to: 'services#pregnancy_babies'

  get '/services/families/:type', to: 'services#families'
  # get '/services/families/help_crisis', to: 'services#families'
  # get '/services/families/childcare', to: 'services#families'
  # get '/services/families/assistance', to: 'services#families'
  # get '/services/families/support', to: 'services#families'

  get '/services/children/:type', to: 'services#children'
  # get '/services/children/help_crisis', to: 'services#children'
  # get '/services/children/child_advocacy', to: 'services#children'
  # get '/services/children/health', to: 'services#children'
  # get '/services/children/support', to: 'services#children'

  get '/programs/learn_more/:id', to: 'programs#learn_more', as: 'program_learn_more'
  get '/services/learn_more/:id', to: 'services#learn_more', as: 'service_learn_more'
  get '/events/learn_more/:id', to: 'events#learn_more', as: 'event_learn_more'
  get '/whats_new_items/learn_more/:id', to: 'whats_new_items#learn_more', as: 'whats_new_item_learn_more'

  get '/services/pregnancy_babies', to: 'services#pregnancy_babies'

  get '/services/families', to: 'services#families'

  get '/services/children', to: 'services#children'

  get '/live', to: 'home#live', as: 'live5210'

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard/pending_and_approved_events', to: 'events#pending_and_approved_events'
  get '/dashboard/pending_and_approved_resources', to: 'resources#pending_and_approved_resources'
  get '/dashboard/manage_programs', to: 'programs#index'
  get '/dashboard/manage_services', to: 'services#index'
  get '/dashboard/manage_tags', to: 'tags#index'
  get '/dashboard/manage_organizations', to: 'organizations#index'
  get '/dashboard/manage_events', to: 'events#index2'
  get '/dashboard/manage_whats_new_items', to: 'whats_new_items#index'
  get '/dashboard/manage_resources', to: 'resources#index2'

  get '/map', to: 'home#map', as: 'map'

  # get '/search', to: 'home#search', as: 'search'
  # post '/search', to: 'home#search'

  get '/surveys', to: 'home#surveys', as: 'surveys'

  get '/contact_submit', to: 'home#submit', as: 'contact_submit'
  match '/contact_mail', to: 'home#contact_mail', via: 'post'

  get 'dashboard/pending_and_approved_events/decline/:id', to: 'events#decline', as: 'decline_event'
  match '/decline_event_mail', to: 'events#decline_mail', via: 'post'

  get 'dashboard/pending_and_approved_resources/decline/:id', to: 'resources#decline', as: 'decline_resource'
  match '/decline_resource_mail', to: 'resources#decline_mail', via: 'post'

  match '/events/:id/admin_approve_resource', to: 'resources#admin_approve_resource', as: 'admin_resource_approve', via: 'post'

  match '/events/:id/admin_approve_event', to: 'events#admin_approve_event', as: 'admin_event_approve', via: 'post'




  resources :tags
  resources :resources
  resources :whats_new_items
  resources :services
  resources :events
  resources :organizations
  resources :programs
  resources :password_resets

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/event.rb
class Event < ApplicationRecord
  serialize :recurring, Hash
  before_save :save_dates
  after_update :send_approved_event_email, :if => :approved_changed?

  def save_dates
    self.start_date = self.start_time.strftime("%Y/%m/%d")
    self.end_date = self.end_time.strftime("%Y/%m/%d")
  end

  def send_approved_event_email
    PendingEventMailer.approved_event_email(self).deliver!
  end

  def recurring=(value)
    if value == "null"
      super(nil)
    elsif RecurringSelect.is_valid_rule?(value)
        super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
        super(nil)
    end
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)
    schedule
  end

  def calendar_events(start_d, end_d)
    if recurring.empty?
        [self]
    else
        schedule(self.start_time).occurrences_between(start_d, end_d + 1.day).map do |date|
            Event.new(id: id, title: title, start_time: date, end_time: date, description: description, address: address)
        end
    end
  end

  scope :by_start_date, -> start_date {
    where('start_date >= (?)', start_date)
    .or(where('start_date <= (?) AND end_date >= (?)', start_date, start_date))}

  scope :by_end_date, -> end_date {
    where('end_date <= (?)', end_date)
    .or(where('start_date <= (?) AND end_date >= (?)', end_date, end_date)) }

  scope :search, -> term {
    if self.has_attribute?(:event_type_id)
      includes(:tags).where('tags.name ILIKE (?) OR title ILIKE (?) OR description ILIKE (?) OR address ILIKE (?)', "%#{term}%", "%#{term}%", "%#{term}%", "%#{term}%").order('title ASC')
    end
  }

  scope :event_location, -> location_id { Event.includes(:locations).where(:locations => {:id => location_id}) }
  scope :approved, -> { where(approved: true) }
  scope :registration, -> registration { where(:registration => registration) }
  scope :cost, -> cost { where(:cost => cost) }
  scope :event_type, -> event_type { where(:event_type_id => event_type) }
  scope :age_group, -> age_id { Event.includes(:age_groups).where(:age_groups => {:id => age_id}) }


  mount_uploader :image, ImageUploader
  mount_uploader :pdf_file, ImageUploader

  has_many :EventTaggings, dependent: :destroy
  has_many :tags, through: :EventTaggings

  has_many :EventAgeGroups, dependent: :destroy
  has_many :age_groups, through: :EventAgeGroups
  has_many :event_locations, dependent: :destroy
  has_many :locations, through: :event_locations

  belongs_to :user, optional: true
  belongs_to :event_type

  geocoded_by :address
  after_validation :geocode

  def location_names
    locations.collect(&:name).join(', ')
  end

  def status
    case approved
    when true
      "approved"
    when false
      "declined"
    else
      "pending"
    end
  end

end

app/models/resource.rb
class Resource < ApplicationRecord
  after_update :send_approved_resource_email, :if => :approved_changed?

  def send_approved_resource_email
    PendingResourceMailer.approved_resource_email(self).deliver!
  end

  scope :resource_location, -> resource_location { where(:resource_location => resource_location) }
  scope :resource_type, -> resource_type { where(:resource_type => resource_type) }
  scope :approved, -> approved { where(:approved => true) }
  scope :resource_topic, -> topic_id { Resource.includes(:topics).where(:topics => {:id => topic_id})}
  scope :resource_age_group, -> age_id { Resource.includes(:age_groups).where(:age_groups => {:id => age_id})}


  mount_uploader :resource_file, ImageUploader

  has_many :ResourceTaggings, dependent: :destroy
  has_many :tags, through: :ResourceTaggings

  has_many :ResourceTopics, dependent: :destroy
  has_many :topics, through: :ResourceTopics

  has_many :ResourceAgeGroups, dependent: :destroy
  has_many :age_groups, through: :ResourceAgeGroups

  belongs_to :user, optional: true

  def self.search(term)
    if term
      joins(:tags).where('tags.name ILIKE (?) OR resource_name ILIKE (?) OR description ILIKE (?)', "%#{term}%", "%#{term}%", "%#{term}%").order('resource_name ASC')
    else
      order('resource_name ASC')
    end
  end

end

app/views/resources/create.html.erb
<h1>Resources#create</h1>
<p>Find me in app/views/resources/create.html.erb</p>

app/views/resources/decline.html.erb
<div class="wholePage">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">

          <h1 class='bree-font'>Decline Resource Request</h1>
          <br>
          <h4 class='font-20'><strong>Name: </strong><%= @resource.resource_name %></h4>
          <h4 class='font-20'><strong>Description: </strong><%= @resource.description %></h4>
          <h4 class='font-20'><strong>Contact Name: </strong><%= @resource.contact_name %></h4>
          <p class="bree-font26">Reason:</p>

          <%= form_tag(decline_resource_mail_path) do %>
        <div class="">
          <div class="contact-form">
          <%= hidden_field_tag :resource, @resource.resource_name %>
          <%= hidden_field_tag :resource_email, @resource.contact_email %>
          <%= text_area_tag :message, nil, {placeholder: "Message", class: "form-control contact-form", rows: 10, :required => true} %>
        </div>
          <%= submit_tag 'Send Message', class:"btn-primary pull-right btn-lg", id:"btn-padding" %>
        </div>

        <% end %>

        </div>
          </div>
          <br>
        </div>



      </div>
    </div>
</div>

<%= render 'partials/footer' %>

app/views/resources/destroy.html.erb
<h1>Resources#destroy</h1>
<p>Find me in app/views/resources/destroy.html.erb</p>

app/views/resources/edit.html.erb
<div class="wholePage">
  <!-- First section div -->
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">

      <%= render 'partials/dash_sidebar' %>

      <% if user_signed_in? %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content">
        <div class="">
            <br>
            <p class="dashboard-headers mobile-font-24">Edit Resource</p>

            <%= form_for @resource do |f| %>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :resource_name,"Resource Name" %>
              <%= f.text_field :resource_name, class: "form-control", :required => true  %>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :feature, "Feature Resource?" %>
              <div class="">
                <%= f.radio_button(:feature, true) %>
                <%= label_tag(:feature, "Yes", class:'radio-spacing') %>
                <%= f.radio_button(:feature, false) %>
                <%= label_tag(:feature, "No", class:'radio-spacing') %>
              </div>
            </div>
            <!--  FEATURE UNTIL add calender -->
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label "Resource is about the situation in: " %>
            <div class="">
              <div class="in-block">

                <%= f.radio_button(:resource_location, "Delta") %>
                <%= label_tag(:resource_location, "Delta", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "BC") %>
                <%= label_tag(:resource_location, "BC", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "Canada") %>
                <%= label_tag(:resource_location, "Canada", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "N/A") %>
                <%= label_tag(:resource_location, "N/A", class:'radio-spacing') %>
              </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label "Resource Type", "Resource Type: " %>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Research") %>
                <%= label_tag(:resource_type, "Research", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Report") %>
                <%= label_tag(:resource_type, "Report", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Tips & Guidelines") %>
                <%= label_tag(:resource_type, "Tips & Guidelines", class:'radio-spacing') %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :Topic, class:'' %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :topic_ids,
                Topic.all,
                :id,
                :topic_name,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :age_group, "Age Group" %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :age_group_ids,
                AgeGroup.all,
                :id,
                :age,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :Tags %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :tag_ids,
                Tag.all,
                :id,
                :name,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :description, class:'' %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <!-- FILE UPLOADER -->
          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :resource_file,"Resource File (pdf)", class: "" %>
            <%= f.file_field :resource_file, style:"color:transparent;"   %>
            <p style="margin-top:2%"><%= File.basename(@resource.resource_file.to_s)  %></p>
          </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :contact_name, "Contact Name" %>
            <%= f.text_field :contact_name, class: 'form-control  ' %>
          </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :contact_email, "Contact Email" %>
            <%= f.email_field :contact_email, class: 'form-control  ' %>
          </div>
          <br>
          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field" style="padding-bottom:10%;">
            <%= f.submit class: 'btn btn-primary form-control  ' %>
          </div>
      </div>
    </div>
    </div>
    <% end %>
    <% else %>
    <%= render 'partials/login_msg' %>
    <% end %>

  </div>
</div>


<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/resources/index2.html.erb
<div class="wholePage">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">
      <%= render 'partials/dash_sidebar' %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white;">
        <% if user_signed_in? %>
        <% if is_admin? %>
        <div class="container-fluid">
          <h1 class="bree-font">Resources</h1>
          <br>
          <% @resources.each do |resource| %>
          <p class="font-16"><%= link_to resource.resource_name, resource_path(resource) %></p>
          <hr>
          <% end %><div class="container-fluid center-flex-content bree-font" style="align-items:center;">
            <%= paginate @resources, window: 2 %>
          </div>
        </div>
        <% else %>
        <div class="container-fluid">
          <h1 class="bree-font">Resources</h1>
          <br>
          <% @resources_public.each do |resource| %>
          <p class="font-16"><%= link_to resource.resource_name, resource_path(resource) %></p>
          <hr>
          <% end %><div class="container-fluid center-flex-content bree-font" style="align-items:center;">
            <%= paginate @resources_public, window: 2 %>
          </div>
        </div>
        <% end %>

        <% else %>
        <%= render 'partials/login_msg' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/resources/new.html.erb
<div class="wholePage">
  <!-- First section div -->
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 content">

      <%= render 'partials/dash_sidebar' %>

      <% if user_signed_in? %>
      <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content">
        <div class="">
            <br>
            <p class="dashboard-headers mobile-font-24">Create New Resource</p>

            <%= form_for @resource do |f| %>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :resource_name, "Resource Name" %>
              <%= f.text_field :resource_name, class: "form-control",  :required => true  %>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :feature, "Feature Resource?" %>
              <div class="">
                <%= f.radio_button(:feature, true) %>
                <%= label_tag(:feature, "Yes", class:'radio-spacing') %>
                <%= f.radio_button(:feature, false, :checked => true) %>
                <%= label_tag(:feature, "No", class:'radio-spacing') %>
              </div>
            </div>
            <!--  FEATURE UNTIL add calender -->
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label "Resource is about the situation in: " %>
            <div class="">
              <div class="in-block">

                <%= f.radio_button(:resource_location, "Delta",:checked => true) %>
                <%= label_tag(:resource_location, "Delta", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "BC") %>
                <%= label_tag(:resource_location, "BC", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "Canada") %>
                <%= label_tag(:resource_location, "Canada", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_location, "N/A") %>
                <%= label_tag(:resource_location, "N/A", class:'radio-spacing') %>
              </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :resource_type, "Resource Type: " %>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Research",:checked => true) %>
                <%= label_tag(:resource_type, "Research", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Report") %>
                <%= label_tag(:resource_type, "Report", class:'radio-spacing') %>
              </div>
              <div class="in-block">
                <%= f.radio_button(:resource_type, "Tips & Guidelines") %>
                <%= label_tag(:resource_type, "Tips & Guidelines", class:'radio-spacing') %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :Topic, class:'' %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :topic_ids,
                Topic.all,
                :id,
                :topic_name,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :age_group, "Age Group" %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :age_group_ids,
                AgeGroup.all,
                :id,
                :age,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
              <%= f.label :Tags %>
              <div class="form-group  dropbox-container">
                <%= f.collection_select :tag_ids,
                Tag.all,
                :id,
                :name,
                {},
                { multiple: true, class: 'chosen-select form-control '}
                %>
              </div>
            </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :description, class:'' %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <!-- FILE UPLOADER -->
          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :resource_file,"Resource File (pdf)", class: "" %>
            <%= f.file_field :resource_file, :required => true  %>
          </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :contact_name, "Contact Name" %>
            <%= f.text_field :contact_name, class: 'form-control  ' %>
          </div>

          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field">
            <%= f.label :contact_email, "Contact Email" %>
            <%= f.email_field :contact_email, class: 'form-control  ' %>
          </div>
          <br>
          <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2  col-md-offset-3 form-field" style="padding-bottom:10%;">
            <%= f.submit class: 'btn btn-primary form-control  ' %>
          </div>
      </div>
    </div>
    </div>
    <% end %>
    <% else %>
    <%= render 'partials/login_msg' %>
    <% end %>

  </div>
</div>


<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/resources/pending_and_approved_resources.html.erb
<div class="wholePage">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 content">

        <%= render 'partials/dash_sidebar' %>

        <div class="col-xs-12 col-sm-9 col-md-9 dash-main-content" style="background-color:white;">
          <% if user_signed_in? %>
          <% if is_admin? %>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="container-fluid">
                <h1 class="bree-font mobile-font-24">Pending Resources</h1>
                <br>
                <% if @resources.count == 0 %>
                <p class="font-16"> There are no Pending Resources at this time.</p>
                <% else %>
                <% @resources.each do |resource| %>

                <p class="font-16"><%= link_to resource.resource_name, resource_path(resource) %></p>
                <div class="flex">

                <%= link_to("Approve", admin_resource_approve_path(resource), :confirm => "Approve Resource?", :method => :post, class:"btn btn-success edit-delete-btn-width form-padding")%>&nbsp
                  <%= link_to "Decline", decline_resource_path(resource), class: 'btn btn-danger edit-delete-btn-width'  %>
                </div>
                  <hr>
                <% end %>
                <% end %>
                <div class="container-fluid center-flex-content bree-font" style="align-items:center;">
                <%= paginate @resources, window: 2 %>
              </div>
              </div>
            </div>
          </div>
          <% end %>
          <% else %>
          <%= render 'partials/login_msg' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/resources/show.html.erb
<div class="wholePage">
    <div class="row">
      <div class="col-xs-12 content">

        <%= render 'partials/dash_sidebar' %>

        <div class="col-xs-12 col-sm-8 col-md-9 dash-main-content" style="background-color:white; margin:auto">
          <% if user_signed_in? %>

          <div class="row">
            <div class="col-xs-12">
              <div class="container-fluid">
                <br>
                <p class="bree-font"><%= @resource.resource_name %></p>
                <p class="font-20"><strong>Feature Resource: </strong>
                  <% if @resource.feature? %>Yes</p>
                    <% else %>
                    No</p>
                <% end %>
                <p class="font-20"><strong>Resource Location: </strong><%= @resource.resource_location %></p>
                <p class="font-20" style="white-space: pre-line;"><strong>Description: </strong><%= @resource.description %></p>
                <p class='font-20'><strong>Topics: </strong><%= @resource.topics.map(&:topic_name).join(', ') %></p>
                <p class='font-20'><strong>Age Groups: </strong><%= @resource.age_groups.map(&:age).join(', ') %></p>
                <p class='font-20'><strong>Tags: </strong><%= @resource.tags.map(&:name).join(', ') %></p>
                <p class="font-20"><strong>Uploaded File: </strong><%= link_to "View File", asset_path(@resource.resource_file) %></p>
                <p class="font-20"><strong>Contact Name: </strong><%= @resource.contact_name %></p>
                <p class="font-20"><strong>Contact Email: </strong><%= @resource.contact_email %></p>

                <br>
                <% if is_admin? %>
                <div class="center-flex-content">
                  <% if @resource.approved != true %>
                    <%= link_to("Approve", admin_resource_approve_path(@resource), :confirm => "Approve Resource?", :method => :post, class:"btn btn-success edit-delete-btn-width form-padding")%>
                      <%= link_to "Decline", decline_resource_path(@resource), class: 'btn btn-danger edit-delete-btn-width' ,style:"margin-left:5%;" %>
                  <% end %>
                </div>
                <br>
                <div class="center-flex-content">

                  <%= link_to 'Edit', edit_resource_path(@resource),
                  class: 'btn btn-success form-padding edit-delete-btn-width',style:"margin-right:5%;"  %>

                  <%= link_to 'Delete', resource_path(@resource),
                  method: :delete,
                  data: {confirm: 'Are you sure?'},
                  class: 'btn btn-danger edit-delete-btn-width', style:'color:white !important;' %>
                </div>
                    <% elsif @resource.approved? %>
                    <% else  %>

                    <div class="center-flex-content">

                      <%= link_to 'Edit', edit_resource_path(@resource),
                      class: 'btn btn-success form-padding edit-delete-btn-width',style:"margin-right:5%;"  %>
                    </div>
                    <% end %>
                    <br>
                    <br>

                <% if is_admin? %><% else %>
                <p class="font-16">
                  * Please Note: You may only edit your request while it is still pending. When your request for a new Resource has been processed any further changes must be done by an Admin.
                </p>
                <br>
                <% end %>

              </div>
            </div>
          </div>

          <% else %>
          <%= render 'partials/login_msg' %>
        </div>
        <% end %>
      </div>
    </div>
</div>

<!-- Rainbow Footer-->

<%= render 'partials/footer' %>

app/views/resources/update.html.erb
<h1>Resources#update</h1>
<p>Find me in app/views/resources/update.html.erb</p>